SUMMARY = "MedPlatform /etc/fw_env.config: where fw_printenv/fw_setenv find the U-Boot environment"
DESCRIPTION = "RAUC's uboot backend marks a slot by calling fw_setenv, which \
reads /etc/fw_env.config to find the U-Boot environment. Without this file the \
backend fails, RAUC cannot determine the boot state of any slot, and reports \
every slot - including the running one - as bad. This recipe writes that file \
for the machine it is built for, addressing the partition by PARTUUID."
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/MIT;md5=0835ade698e0bcf8506ecda2f7b4f302"

S = "${WORKDIR}"

# The content is a PARTUUID from one machine's partition table. Two machines
# sharing a TMPDIR would otherwise write the same package name into the same
# all/ deploy directory with different contents, and the second build would
# silently overwrite the first - the same hazard med-data-volume_1.0.bb records.
PACKAGE_ARCH = "${MACHINE_ARCH}"

# The tool this file is data for. It is the first dependency this layer takes
# outside oe-core, and LAYERDEPENDS says so rather than leaving it implicit.
RDEPENDS:${PN} = "libubootenv-bin"

# Declared per machine in conf/layer.conf, alongside the .wks that creates the
# partition this UUID names - one value, two consumers, one layer.
MED_UBOOT_ENV_PARTUUID ?= ""

# CONFIG_ENV_SIZE. 0x2000 is U-Boot's default and no stm32mp defconfig
# overrides it; ST's own fw_env.config.mmc declares the same value. Both were
# indications rather than proof until the board confirmed them: with this file
# in place, "fw_setenv BOOT_ORDER 'A B'" followed by fw_printenv round-trips,
# which exercises the address, the size and the two-entry redundant format at
# once.
MED_UBOOT_ENV_SIZE ?= "0x2000"

# Copy 1 sits one ENV_SIZE further back than copy 0, so it is derived rather
# than written down twice - a hand-written -0x4000 would silently stop matching
# the moment the size above changed.
MED_UBOOT_ENV_REDUND_OFFSET = "${@'0x%x' % (2 * int(d.getVar('MED_UBOOT_ENV_SIZE'), 16))}"

do_install() {
    if [ -z "${MED_UBOOT_ENV_PARTUUID}" ]; then
        bbfatal "MED_UBOOT_ENV_PARTUUID is empty for MACHINE=${MACHINE}. This \
recipe writes the address of a specific partition; declare the UUID in \
meta-med-bsp/conf/layer.conf next to the .wks that creates it, or do not \
install this package on this machine."
    fi

    install -d ${D}${sysconfdir}
    cat > ${D}${sysconfdir}/fw_env.config <<CONFIG
# Generated by med-uboot-env-config for MACHINE=${MACHINE}. Do not edit here.
#
# Addressed by PARTUUID, never by partlabel, and that is not style. On a board
# with an eMMC carrying a factory OpenSTLinux image - this one - the GPT names
# bootfs, rootfs, vendorfs, u-boot-env, fip-a and fip-b exist on *both* disks,
# and /dev/disk/by-partlabel/ is one flat namespace across every block device,
# so udev gives each colliding name to whichever disk enumerated first. Which
# disk that is was measured twice and came out differently both times: the SD
# card was mmcblk1 and the eMMC mmcblk0 on one boot, mmcblk0 and mmcblk2 on the
# next, same hardware, no configuration change. Device enumeration is a race.
#
# And for this partition the race is lost, measured on the board 2026-08-18:
#
#     readlink -f /dev/disk/by-partlabel/u-boot-env   ->  /dev/mmcblk2p5
#     readlink -f /dev/disk/by-partuuid/d7ba3548-...  ->  /dev/mmcblk0p7
#
# mmcblk2 is the factory eMMC. ST's own fw_env.config.mmc, addressing this by
# partlabel, would therefore have pointed fw_setenv at *another operating
# system's* bootloader environment - and it would have worked, silently, until
# someone wondered why a slot switch never took effect. A PARTUUID is unique by
# construction, so it is the only stable address here.
#
# The two entries are required, not optional. ST's U-Boot is built with
# CONFIG_SYS_REDUNDAND_ENVIRONMENT=y, which changes the on-media format (a
# flags byte after the CRC), so a single-entry config would not merely lose
# redundancy - it would fail the CRC and read nothing.
#
# The offsets come from U-Boot's own env/mmc.c, because ST's shipped
# fw_env.config.mmc gets them wrong: it lists -0x2000 twice, which points both
# copies at the same 8 KiB. mmc_offset_try_partition() computes
#
#     (info.start + info.size - (1 + copy) * len) * info.blksz
#
# with len = CONFIG_ENV_SIZE - "use the top of the partition for the
# environment" - so copy 0 is the last ENV_SIZE bytes of the partition and copy
# 1 is the ENV_SIZE bytes before it. ST's patch to env/mmc.c only adds a
# fallback that matches the partition by TYPE GUID; it leaves this formula
# untouched, and U-Boot reaches this partition by name first through
# the devicetree property u-boot,mmc-env-partition = u-boot-env anyway.
#
# Device                                              Offset      Env. size
/dev/disk/by-partuuid/${MED_UBOOT_ENV_PARTUUID}    -${MED_UBOOT_ENV_SIZE}    ${MED_UBOOT_ENV_SIZE}
/dev/disk/by-partuuid/${MED_UBOOT_ENV_PARTUUID}    -${MED_UBOOT_ENV_REDUND_OFFSET}    ${MED_UBOOT_ENV_SIZE}
CONFIG
    chmod 0644 ${D}${sysconfdir}/fw_env.config
}

FILES:${PN} = "${sysconfdir}/fw_env.config"

# ST's u-boot-fw-config-stm32mp ships fw_env.config.mmc/.nand/.nor and never
# fw_env.config, so there is no file conflict with it - the two packages can
# and do coexist.
