SUMMARY = "MedPlatform CPU frequency policy for machines whose DVFS costs samples"
DESCRIPTION = "Pins the cpufreq governor at boot through systemd-tmpfiles. On the \
STM32MP257 the default governor (schedutil) switched the Cortex-A35 between its \
two operating points ~86 times a second, and host-timed acquisition lost ~0.7% \
of its samples to it; with no switching the loss fell to <=0.003%."
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/MIT;md5=0835ade698e0bcf8506ecda2f7b4f302"

S = "${WORKDIR}"

# The value is a fact about one machine's DVFS, declared per machine in
# conf/layer.conf; a machine that does not declare it does not install this.
PACKAGE_ARCH = "${MACHINE_ARCH}"

MED_CPUFREQ_GOVERNOR ?= ""

do_install() {
    if [ -z "${MED_CPUFREQ_GOVERNOR}" ]; then
        bbfatal "MED_CPUFREQ_GOVERNOR is not set for ${MACHINE}: declare it in meta-med-bsp/conf/layer.conf or do not install ${PN}"
    fi
    install -d ${D}${nonarch_libdir}/tmpfiles.d
    # "w" writes the value into an existing file and accepts a glob, so every
    # cpufreq policy the kernel exposes gets it - on this SoC there is one.
    # A runtime write, not CONFIG_CPU_FREQ_DEFAULT_GOV_*: the kernel lives on
    # med-boot, which no update bundle replaces, and this has to reach a
    # fielded device through the A/B path like any other correction.
    printf '%s\n' \
        "# ${SUMMARY}" \
        "# Generated by ${PN} for ${MACHINE}. See BRINGUP_AFE.md §6.5." \
        "w /sys/devices/system/cpu/cpufreq/policy*/scaling_governor - - - - ${MED_CPUFREQ_GOVERNOR}" \
        > ${D}${nonarch_libdir}/tmpfiles.d/med-cpufreq.conf
}

FILES:${PN} = "${nonarch_libdir}/tmpfiles.d"
